### ISSUE TITLE
Model generation fails silently if non-valid model is generated.

### ISSUE THREAD

**Issue by blt** [datamapper/dm-sweatshop#5]
Presume we have the following model:

<pre>
  class User
    include DataMapper::Resource

    property :id, Serial
    property :username, String, :length => 1..20
    property :email,    String
    property :password, String
  end
</pre>

and this fixture:

<pre>
User.fixture {{
    :username              => (username = /\w+/.gen),
    :email                 => "#{username}@example.com",
    :password              => (password = /\w+/.gen),
    :password_confirmation => password
  }}
</pre>

we will occasionally generate invalid models, with no indication to the user that this is the case (other than to inspect every .make'd model).

**Comment by dkubb** [comment]
@blt sorry for not responding to this sooner.

Did you ever find out what the problem was? The specification for the username could return a string with a length greater than 20 characters, so that would definitely be suspect.

But you're right. We should warn or raise or something when the generated object can't be saved.

**Comment by blt** [comment]
Oh my. That was so long ago and I don't use DataMapper any longer. I don't recall if I solved this problem or moved on as a result of it.
